namespace FaviconForge
{
    partial class FaviconForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            previewTimer = new System.Windows.Forms.Timer(components);
            panelTop = new Panel();
            lblSourceInfo = new Label();
            btnOpenSource = new Button();
            tabsSettings = new TabControl();
            tabGeneral = new TabPage();
            chkPixelArt = new CheckBox();
            btnThemeColor = new Button();
            lblThemeColorCap = new Label();
            txtPathPrefix = new TextBox();
            lblPathPrefix = new Label();
            tabFavicon = new TabPage();
            trkFavRadius = new TrackBar();
            lblFavRadius = new Label();
            trkFavMargin = new TrackBar();
            lblFavMargin = new Label();
            btnFavColor = new Button();
            chkFavBg = new CheckBox();
            tabIos = new TabPage();
            txtAppleTitle = new TextBox();
            lblAppleTitleCap = new Label();
            trkIosMargin = new TrackBar();
            lblIosMargin = new Label();
            btnIosColor = new Button();
            chkIosBg = new CheckBox();
            tabAndroid = new TabPage();
            txtAndroidShort = new TextBox();
            lblAndroidShortCap = new Label();
            txtAndroidName = new TextBox();
            lblAndroidNameCap = new Label();
            chkAndroidCircle = new CheckBox();
            trkAndroidMargin = new TrackBar();
            lblAndroidMargin = new Label();
            btnAndroidColor = new Button();
            chkAndroidBg = new CheckBox();
            tabWindows = new TabPage();
            trkTileMargin = new TrackBar();
            lblTileMargin = new Label();
            btnTileColor = new Button();
            lblTileColorCap = new Label();
            tabSafari = new TabPage();
            trkSafariThreshold = new TrackBar();
            lblSafariThreshold = new Label();
            btnSafariColor = new Button();
            lblSafariColorCap = new Label();
            panelBottom = new Panel();
            txtHtml = new TextBox();
            lblHtml = new Label();
            btnCopyHtml = new Button();
            btnGenerateFolder = new Button();
            btnGenerateZip = new Button();
            flowPreviews = new FlowLayoutPanel();
            pnlPrevBrowserLight = new Panel();
            picPrevBrowserLight = new PictureBox();
            lblPrevBrowserLight = new Label();
            pnlPrevBrowserDark = new Panel();
            picPrevBrowserDark = new PictureBox();
            lblPrevBrowserDark = new Label();
            pnlPrevSearchLight = new Panel();
            picPrevSearchLight = new PictureBox();
            lblPrevSearchLight = new Label();
            pnlPrevSearchDark = new Panel();
            picPrevSearchDark = new PictureBox();
            lblPrevSearchDark = new Label();
            pnlPrevIos = new Panel();
            picPrevIos = new PictureBox();
            lblPrevIos = new Label();
            pnlPrevAndroid = new Panel();
            picPrevAndroid = new PictureBox();
            lblPrevAndroid = new Label();
            pnlPrevSplash = new Panel();
            picPrevSplash = new PictureBox();
            lblPrevSplash = new Label();
            pnlPrevSwitcher = new Panel();
            picPrevSwitcher = new PictureBox();
            lblPrevSwitcher = new Label();
            pnlPrevTile = new Panel();
            picPrevTile = new PictureBox();
            lblPrevTile = new Label();
            pnlPrevSafari = new Panel();
            picPrevSafari = new PictureBox();
            lblPrevSafari = new Label();
            panelTop.SuspendLayout();
            tabsSettings.SuspendLayout();
            tabGeneral.SuspendLayout();
            tabFavicon.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)trkFavRadius).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trkFavMargin).BeginInit();
            tabIos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)trkIosMargin).BeginInit();
            tabAndroid.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)trkAndroidMargin).BeginInit();
            tabWindows.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)trkTileMargin).BeginInit();
            tabSafari.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)trkSafariThreshold).BeginInit();
            panelBottom.SuspendLayout();
            flowPreviews.SuspendLayout();
            pnlPrevBrowserLight.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevBrowserLight).BeginInit();
            pnlPrevBrowserDark.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevBrowserDark).BeginInit();
            pnlPrevSearchLight.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevSearchLight).BeginInit();
            pnlPrevSearchDark.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevSearchDark).BeginInit();
            pnlPrevIos.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevIos).BeginInit();
            pnlPrevAndroid.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevAndroid).BeginInit();
            pnlPrevSplash.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevSplash).BeginInit();
            pnlPrevSwitcher.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevSwitcher).BeginInit();
            pnlPrevTile.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevTile).BeginInit();
            pnlPrevSafari.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPrevSafari).BeginInit();
            SuspendLayout();
            previewTimer.Interval = 120;
            panelTop.Controls.Add(lblSourceInfo);
            panelTop.Controls.Add(btnOpenSource);
            panelTop.Dock = DockStyle.Top;
            panelTop.Location = new Point(0, 0);
            panelTop.Name = "panelTop";
            panelTop.Size = new Size(1164, 46);
            panelTop.TabIndex = 0;
            lblSourceInfo.AutoSize = true;
            lblSourceInfo.Location = new Point(196, 16);
            lblSourceInfo.Name = "lblSourceInfo";
            lblSourceInfo.Size = new Size(257, 15);
            lblSourceInfo.TabIndex = 1;
            lblSourceInfo.Text = "Перетащите изображение или откройте файл";
            btnOpenSource.Location = new Point(10, 9);
            btnOpenSource.Name = "btnOpenSource";
            btnOpenSource.Size = new Size(170, 28);
            btnOpenSource.TabIndex = 0;
            btnOpenSource.Text = "Открыть изображение...";
            btnOpenSource.UseVisualStyleBackColor = true;
            tabsSettings.Controls.Add(tabGeneral);
            tabsSettings.Controls.Add(tabFavicon);
            tabsSettings.Controls.Add(tabIos);
            tabsSettings.Controls.Add(tabAndroid);
            tabsSettings.Controls.Add(tabWindows);
            tabsSettings.Controls.Add(tabSafari);
            tabsSettings.Dock = DockStyle.Left;
            tabsSettings.Location = new Point(0, 46);
            tabsSettings.Name = "tabsSettings";
            tabsSettings.SelectedIndex = 0;
            tabsSettings.Size = new Size(380, 451);
            tabsSettings.TabIndex = 1;
            tabGeneral.Controls.Add(chkPixelArt);
            tabGeneral.Controls.Add(btnThemeColor);
            tabGeneral.Controls.Add(lblThemeColorCap);
            tabGeneral.Controls.Add(txtPathPrefix);
            tabGeneral.Controls.Add(lblPathPrefix);
            tabGeneral.Location = new Point(4, 24);
            tabGeneral.Name = "tabGeneral";
            tabGeneral.Padding = new Padding(3);
            tabGeneral.Size = new Size(372, 423);
            tabGeneral.TabIndex = 0;
            tabGeneral.Text = "Общие";
            tabGeneral.UseVisualStyleBackColor = true;
            chkPixelArt.AutoSize = true;
            chkPixelArt.Location = new Point(12, 124);
            chkPixelArt.Name = "chkPixelArt";
            chkPixelArt.Size = new Size(247, 19);
            chkPixelArt.TabIndex = 4;
            chkPixelArt.Text = "Пиксельный режим (без сглаживания)";
            chkPixelArt.UseVisualStyleBackColor = true;
            btnThemeColor.BackColor = Color.White;
            btnThemeColor.Location = new Point(12, 82);
            btnThemeColor.Name = "btnThemeColor";
            btnThemeColor.Size = new Size(140, 28);
            btnThemeColor.TabIndex = 3;
            btnThemeColor.Tag = "notheme";
            btnThemeColor.Text = "#ffffff";
            btnThemeColor.UseVisualStyleBackColor = false;
            lblThemeColorCap.AutoSize = true;
            lblThemeColorCap.Location = new Point(12, 64);
            lblThemeColorCap.Name = "lblThemeColorCap";
            lblThemeColorCap.Size = new Size(150, 15);
            lblThemeColorCap.TabIndex = 2;
            lblThemeColorCap.Text = "Цвет темы (theme-color):";
            txtPathPrefix.Location = new Point(12, 32);
            txtPathPrefix.Name = "txtPathPrefix";
            txtPathPrefix.Size = new Size(340, 23);
            txtPathPrefix.TabIndex = 1;
            txtPathPrefix.Text = "/";
            lblPathPrefix.AutoSize = true;
            lblPathPrefix.Location = new Point(12, 14);
            lblPathPrefix.Name = "lblPathPrefix";
            lblPathPrefix.Size = new Size(151, 15);
            lblPathPrefix.TabIndex = 0;
            lblPathPrefix.Text = "Путь до иконок на сайте:";
            tabFavicon.Controls.Add(trkFavRadius);
            tabFavicon.Controls.Add(lblFavRadius);
            tabFavicon.Controls.Add(trkFavMargin);
            tabFavicon.Controls.Add(lblFavMargin);
            tabFavicon.Controls.Add(btnFavColor);
            tabFavicon.Controls.Add(chkFavBg);
            tabFavicon.Location = new Point(4, 24);
            tabFavicon.Name = "tabFavicon";
            tabFavicon.Padding = new Padding(3);
            tabFavicon.Size = new Size(372, 423);
            tabFavicon.TabIndex = 1;
            tabFavicon.Text = "Favicon";
            tabFavicon.UseVisualStyleBackColor = true;
            trkFavRadius.Location = new Point(8, 166);
            trkFavRadius.Maximum = 50;
            trkFavRadius.Name = "trkFavRadius";
            trkFavRadius.Size = new Size(348, 45);
            trkFavRadius.TabIndex = 5;
            trkFavRadius.TickFrequency = 5;
            lblFavRadius.AutoSize = true;
            lblFavRadius.Location = new Point(12, 148);
            lblFavRadius.Name = "lblFavRadius";
            lblFavRadius.Size = new Size(95, 15);
            lblFavRadius.TabIndex = 4;
            lblFavRadius.Text = "Скругление: 0%";
            trkFavMargin.Location = new Point(8, 98);
            trkFavMargin.Maximum = 40;
            trkFavMargin.Name = "trkFavMargin";
            trkFavMargin.Size = new Size(348, 45);
            trkFavMargin.TabIndex = 3;
            trkFavMargin.TickFrequency = 5;
            lblFavMargin.AutoSize = true;
            lblFavMargin.Location = new Point(12, 80);
            lblFavMargin.Name = "lblFavMargin";
            lblFavMargin.Size = new Size(66, 15);
            lblFavMargin.TabIndex = 2;
            lblFavMargin.Text = "Отступ: 0%";
            btnFavColor.BackColor = Color.White;
            btnFavColor.Location = new Point(12, 38);
            btnFavColor.Name = "btnFavColor";
            btnFavColor.Size = new Size(140, 28);
            btnFavColor.TabIndex = 1;
            btnFavColor.Tag = "notheme";
            btnFavColor.Text = "#ffffff";
            btnFavColor.UseVisualStyleBackColor = false;
            chkFavBg.AutoSize = true;
            chkFavBg.Location = new Point(12, 14);
            chkFavBg.Name = "chkFavBg";
            chkFavBg.Size = new Size(124, 19);
            chkFavBg.TabIndex = 0;
            chkFavBg.Text = "Фоновая заливка";
            chkFavBg.UseVisualStyleBackColor = true;
            tabIos.Controls.Add(txtAppleTitle);
            tabIos.Controls.Add(lblAppleTitleCap);
            tabIos.Controls.Add(trkIosMargin);
            tabIos.Controls.Add(lblIosMargin);
            tabIos.Controls.Add(btnIosColor);
            tabIos.Controls.Add(chkIosBg);
            tabIos.Location = new Point(4, 24);
            tabIos.Name = "tabIos";
            tabIos.Padding = new Padding(3);
            tabIos.Size = new Size(372, 423);
            tabIos.TabIndex = 2;
            tabIos.Text = "iOS";
            tabIos.UseVisualStyleBackColor = true;
            txtAppleTitle.Location = new Point(12, 168);
            txtAppleTitle.Name = "txtAppleTitle";
            txtAppleTitle.Size = new Size(340, 23);
            txtAppleTitle.TabIndex = 5;
            txtAppleTitle.Text = "My App";
            lblAppleTitleCap.AutoSize = true;
            lblAppleTitleCap.Location = new Point(12, 150);
            lblAppleTitleCap.Name = "lblAppleTitleCap";
            lblAppleTitleCap.Size = new Size(160, 15);
            lblAppleTitleCap.TabIndex = 4;
            lblAppleTitleCap.Text = "Имя под иконкой (Apple):";
            trkIosMargin.Location = new Point(8, 98);
            trkIosMargin.Maximum = 40;
            trkIosMargin.Name = "trkIosMargin";
            trkIosMargin.Size = new Size(348, 45);
            trkIosMargin.TabIndex = 3;
            trkIosMargin.TickFrequency = 5;
            trkIosMargin.Value = 10;
            lblIosMargin.AutoSize = true;
            lblIosMargin.Location = new Point(12, 80);
            lblIosMargin.Name = "lblIosMargin";
            lblIosMargin.Size = new Size(72, 15);
            lblIosMargin.TabIndex = 2;
            lblIosMargin.Text = "Отступ: 10%";
            btnIosColor.BackColor = Color.White;
            btnIosColor.Location = new Point(12, 38);
            btnIosColor.Name = "btnIosColor";
            btnIosColor.Size = new Size(140, 28);
            btnIosColor.TabIndex = 1;
            btnIosColor.Tag = "notheme";
            btnIosColor.Text = "#ffffff";
            btnIosColor.UseVisualStyleBackColor = false;
            chkIosBg.AutoSize = true;
            chkIosBg.Checked = true;
            chkIosBg.CheckState = CheckState.Checked;
            chkIosBg.Location = new Point(12, 14);
            chkIosBg.Name = "chkIosBg";
            chkIosBg.Size = new Size(124, 19);
            chkIosBg.TabIndex = 0;
            chkIosBg.Text = "Фоновая заливка";
            chkIosBg.UseVisualStyleBackColor = true;
            tabAndroid.Controls.Add(txtAndroidShort);
            tabAndroid.Controls.Add(lblAndroidShortCap);
            tabAndroid.Controls.Add(txtAndroidName);
            tabAndroid.Controls.Add(lblAndroidNameCap);
            tabAndroid.Controls.Add(chkAndroidCircle);
            tabAndroid.Controls.Add(trkAndroidMargin);
            tabAndroid.Controls.Add(lblAndroidMargin);
            tabAndroid.Controls.Add(btnAndroidColor);
            tabAndroid.Controls.Add(chkAndroidBg);
            tabAndroid.Location = new Point(4, 24);
            tabAndroid.Name = "tabAndroid";
            tabAndroid.Padding = new Padding(3);
            tabAndroid.Size = new Size(372, 423);
            tabAndroid.TabIndex = 3;
            tabAndroid.Text = "Android";
            tabAndroid.UseVisualStyleBackColor = true;
            txtAndroidShort.Location = new Point(12, 80);
            txtAndroidShort.Name = "txtAndroidShort";
            txtAndroidShort.Size = new Size(340, 23);
            txtAndroidShort.TabIndex = 3;
            txtAndroidShort.Text = "App";
            lblAndroidShortCap.AutoSize = true;
            lblAndroidShortCap.Location = new Point(12, 62);
            lblAndroidShortCap.Name = "lblAndroidShortCap";
            lblAndroidShortCap.Size = new Size(170, 15);
            lblAndroidShortCap.TabIndex = 2;
            lblAndroidShortCap.Text = "Короткое имя (short name):";
            txtAndroidName.Location = new Point(12, 32);
            txtAndroidName.Name = "txtAndroidName";
            txtAndroidName.Size = new Size(340, 23);
            txtAndroidName.TabIndex = 1;
            txtAndroidName.Text = "My Application";
            lblAndroidNameCap.AutoSize = true;
            lblAndroidNameCap.Location = new Point(12, 14);
            lblAndroidNameCap.Name = "lblAndroidNameCap";
            lblAndroidNameCap.Size = new Size(110, 15);
            lblAndroidNameCap.TabIndex = 0;
            lblAndroidNameCap.Text = "Название (name):";
            chkAndroidCircle.AutoSize = true;
            chkAndroidCircle.Location = new Point(12, 250);
            chkAndroidCircle.Name = "chkAndroidCircle";
            chkAndroidCircle.Size = new Size(115, 19);
            chkAndroidCircle.TabIndex = 8;
            chkAndroidCircle.Text = "Круглая иконка";
            chkAndroidCircle.UseVisualStyleBackColor = true;
            trkAndroidMargin.Location = new Point(8, 198);
            trkAndroidMargin.Maximum = 40;
            trkAndroidMargin.Name = "trkAndroidMargin";
            trkAndroidMargin.Size = new Size(348, 45);
            trkAndroidMargin.TabIndex = 7;
            trkAndroidMargin.TickFrequency = 5;
            lblAndroidMargin.AutoSize = true;
            lblAndroidMargin.Location = new Point(12, 180);
            lblAndroidMargin.Name = "lblAndroidMargin";
            lblAndroidMargin.Size = new Size(66, 15);
            lblAndroidMargin.TabIndex = 6;
            lblAndroidMargin.Text = "Отступ: 0%";
            btnAndroidColor.BackColor = Color.White;
            btnAndroidColor.Location = new Point(12, 138);
            btnAndroidColor.Name = "btnAndroidColor";
            btnAndroidColor.Size = new Size(140, 28);
            btnAndroidColor.TabIndex = 5;
            btnAndroidColor.Tag = "notheme";
            btnAndroidColor.Text = "#ffffff";
            btnAndroidColor.UseVisualStyleBackColor = false;
            chkAndroidBg.AutoSize = true;
            chkAndroidBg.Location = new Point(12, 114);
            chkAndroidBg.Name = "chkAndroidBg";
            chkAndroidBg.Size = new Size(124, 19);
            chkAndroidBg.TabIndex = 4;
            chkAndroidBg.Text = "Фоновая заливка";
            chkAndroidBg.UseVisualStyleBackColor = true;
            tabWindows.Controls.Add(trkTileMargin);
            tabWindows.Controls.Add(lblTileMargin);
            tabWindows.Controls.Add(btnTileColor);
            tabWindows.Controls.Add(lblTileColorCap);
            tabWindows.Location = new Point(4, 24);
            tabWindows.Name = "tabWindows";
            tabWindows.Padding = new Padding(3);
            tabWindows.Size = new Size(372, 423);
            tabWindows.TabIndex = 4;
            tabWindows.Text = "Windows";
            tabWindows.UseVisualStyleBackColor = true;
            trkTileMargin.Location = new Point(8, 92);
            trkTileMargin.Maximum = 40;
            trkTileMargin.Name = "trkTileMargin";
            trkTileMargin.Size = new Size(348, 45);
            trkTileMargin.TabIndex = 3;
            trkTileMargin.TickFrequency = 5;
            trkTileMargin.Value = 20;
            lblTileMargin.AutoSize = true;
            lblTileMargin.Location = new Point(12, 74);
            lblTileMargin.Name = "lblTileMargin";
            lblTileMargin.Size = new Size(72, 15);
            lblTileMargin.TabIndex = 2;
            lblTileMargin.Text = "Отступ: 20%";
            btnTileColor.BackColor = Color.FromArgb(45, 137, 239);
            btnTileColor.ForeColor = Color.White;
            btnTileColor.Location = new Point(12, 32);
            btnTileColor.Name = "btnTileColor";
            btnTileColor.Size = new Size(140, 28);
            btnTileColor.TabIndex = 1;
            btnTileColor.Tag = "notheme";
            btnTileColor.Text = "#2d89ef";
            btnTileColor.UseVisualStyleBackColor = false;
            lblTileColorCap.AutoSize = true;
            lblTileColorCap.Location = new Point(12, 14);
            lblTileColorCap.Name = "lblTileColorCap";
            lblTileColorCap.Size = new Size(82, 15);
            lblTileColorCap.TabIndex = 0;
            lblTileColorCap.Text = "Цвет плитки:";
            tabSafari.Controls.Add(trkSafariThreshold);
            tabSafari.Controls.Add(lblSafariThreshold);
            tabSafari.Controls.Add(btnSafariColor);
            tabSafari.Controls.Add(lblSafariColorCap);
            tabSafari.Location = new Point(4, 24);
            tabSafari.Name = "tabSafari";
            tabSafari.Padding = new Padding(3);
            tabSafari.Size = new Size(372, 423);
            tabSafari.TabIndex = 5;
            tabSafari.Text = "Safari";
            tabSafari.UseVisualStyleBackColor = true;
            trkSafariThreshold.Location = new Point(8, 92);
            trkSafariThreshold.Maximum = 255;
            trkSafariThreshold.Name = "trkSafariThreshold";
            trkSafariThreshold.Size = new Size(348, 45);
            trkSafariThreshold.TabIndex = 3;
            trkSafariThreshold.TickFrequency = 16;
            trkSafariThreshold.Value = 128;
            lblSafariThreshold.AutoSize = true;
            lblSafariThreshold.Location = new Point(12, 74);
            lblSafariThreshold.Name = "lblSafariThreshold";
            lblSafariThreshold.Size = new Size(112, 15);
            lblSafariThreshold.TabIndex = 2;
            lblSafariThreshold.Text = "Порог силуэта: 128";
            btnSafariColor.BackColor = Color.FromArgb(91, 186, 213);
            btnSafariColor.Location = new Point(12, 32);
            btnSafariColor.Name = "btnSafariColor";
            btnSafariColor.Size = new Size(140, 28);
            btnSafariColor.TabIndex = 1;
            btnSafariColor.Tag = "notheme";
            btnSafariColor.Text = "#5bbad5";
            btnSafariColor.UseVisualStyleBackColor = false;
            lblSafariColorCap.AutoSize = true;
            lblSafariColorCap.Location = new Point(12, 14);
            lblSafariColorCap.Name = "lblSafariColorCap";
            lblSafariColorCap.Size = new Size(107, 15);
            lblSafariColorCap.TabIndex = 0;
            lblSafariColorCap.Text = "Цвет pinned tab:";
            panelBottom.Controls.Add(txtHtml);
            panelBottom.Controls.Add(lblHtml);
            panelBottom.Controls.Add(btnCopyHtml);
            panelBottom.Controls.Add(btnGenerateFolder);
            panelBottom.Controls.Add(btnGenerateZip);
            panelBottom.Dock = DockStyle.Bottom;
            panelBottom.Location = new Point(0, 497);
            panelBottom.Name = "panelBottom";
            panelBottom.Size = new Size(1164, 224);
            panelBottom.TabIndex = 2;
            txtHtml.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            txtHtml.Font = new Font("Consolas", 9F);
            txtHtml.Location = new Point(10, 70);
            txtHtml.Multiline = true;
            txtHtml.Name = "txtHtml";
            txtHtml.ReadOnly = true;
            txtHtml.ScrollBars = ScrollBars.Both;
            txtHtml.Size = new Size(1144, 144);
            txtHtml.TabIndex = 4;
            txtHtml.WordWrap = false;
            lblHtml.AutoSize = true;
            lblHtml.Location = new Point(10, 50);
            lblHtml.Name = "lblHtml";
            lblHtml.Size = new Size(189, 15);
            lblHtml.TabIndex = 3;
            lblHtml.Text = "HTML-код для вставки в <head>:";
            btnCopyHtml.Location = new Point(406, 10);
            btnCopyHtml.Name = "btnCopyHtml";
            btnCopyHtml.Size = new Size(170, 32);
            btnCopyHtml.TabIndex = 2;
            btnCopyHtml.Text = "Копировать HTML";
            btnCopyHtml.UseVisualStyleBackColor = true;
            btnGenerateFolder.Location = new Point(208, 10);
            btnGenerateFolder.Name = "btnGenerateFolder";
            btnGenerateFolder.Size = new Size(190, 32);
            btnGenerateFolder.TabIndex = 1;
            btnGenerateFolder.Text = "Сгенерировать в папку...";
            btnGenerateFolder.UseVisualStyleBackColor = true;
            btnGenerateZip.Location = new Point(10, 10);
            btnGenerateZip.Name = "btnGenerateZip";
            btnGenerateZip.Size = new Size(190, 32);
            btnGenerateZip.TabIndex = 0;
            btnGenerateZip.Text = "Сгенерировать ZIP...";
            btnGenerateZip.UseVisualStyleBackColor = true;
            flowPreviews.AutoScroll = true;
            flowPreviews.Controls.Add(pnlPrevBrowserLight);
            flowPreviews.Controls.Add(pnlPrevBrowserDark);
            flowPreviews.Controls.Add(pnlPrevSearchLight);
            flowPreviews.Controls.Add(pnlPrevSearchDark);
            flowPreviews.Controls.Add(pnlPrevIos);
            flowPreviews.Controls.Add(pnlPrevAndroid);
            flowPreviews.Controls.Add(pnlPrevSplash);
            flowPreviews.Controls.Add(pnlPrevSwitcher);
            flowPreviews.Controls.Add(pnlPrevTile);
            flowPreviews.Controls.Add(pnlPrevSafari);
            flowPreviews.Dock = DockStyle.Fill;
            flowPreviews.Location = new Point(380, 46);
            flowPreviews.Name = "flowPreviews";
            flowPreviews.Padding = new Padding(8);
            flowPreviews.Size = new Size(784, 451);
            flowPreviews.TabIndex = 3;
            pnlPrevBrowserLight.Controls.Add(picPrevBrowserLight);
            pnlPrevBrowserLight.Controls.Add(lblPrevBrowserLight);
            pnlPrevBrowserLight.Location = new Point(11, 11);
            pnlPrevBrowserLight.Name = "pnlPrevBrowserLight";
            pnlPrevBrowserLight.Size = new Size(236, 184);
            pnlPrevBrowserLight.TabIndex = 0;
            picPrevBrowserLight.BackColor = Color.White;
            picPrevBrowserLight.BorderStyle = BorderStyle.FixedSingle;
            picPrevBrowserLight.Location = new Point(8, 28);
            picPrevBrowserLight.Name = "picPrevBrowserLight";
            picPrevBrowserLight.Size = new Size(220, 150);
            picPrevBrowserLight.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevBrowserLight.TabIndex = 1;
            picPrevBrowserLight.TabStop = false;
            lblPrevBrowserLight.Dock = DockStyle.Top;
            lblPrevBrowserLight.Location = new Point(0, 0);
            lblPrevBrowserLight.Name = "lblPrevBrowserLight";
            lblPrevBrowserLight.Size = new Size(236, 24);
            lblPrevBrowserLight.TabIndex = 0;
            lblPrevBrowserLight.Text = "Браузер - светлая тема";
            lblPrevBrowserLight.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevBrowserDark.Controls.Add(picPrevBrowserDark);
            pnlPrevBrowserDark.Controls.Add(lblPrevBrowserDark);
            pnlPrevBrowserDark.Location = new Point(253, 11);
            pnlPrevBrowserDark.Name = "pnlPrevBrowserDark";
            pnlPrevBrowserDark.Size = new Size(236, 184);
            pnlPrevBrowserDark.TabIndex = 1;
            picPrevBrowserDark.BackColor = Color.White;
            picPrevBrowserDark.BorderStyle = BorderStyle.FixedSingle;
            picPrevBrowserDark.Location = new Point(8, 28);
            picPrevBrowserDark.Name = "picPrevBrowserDark";
            picPrevBrowserDark.Size = new Size(220, 150);
            picPrevBrowserDark.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevBrowserDark.TabIndex = 1;
            picPrevBrowserDark.TabStop = false;
            lblPrevBrowserDark.Dock = DockStyle.Top;
            lblPrevBrowserDark.Location = new Point(0, 0);
            lblPrevBrowserDark.Name = "lblPrevBrowserDark";
            lblPrevBrowserDark.Size = new Size(236, 24);
            lblPrevBrowserDark.TabIndex = 0;
            lblPrevBrowserDark.Text = "Браузер - тёмная тема";
            lblPrevBrowserDark.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevSearchLight.Controls.Add(picPrevSearchLight);
            pnlPrevSearchLight.Controls.Add(lblPrevSearchLight);
            pnlPrevSearchLight.Location = new Point(495, 11);
            pnlPrevSearchLight.Name = "pnlPrevSearchLight";
            pnlPrevSearchLight.Size = new Size(236, 184);
            pnlPrevSearchLight.TabIndex = 2;
            picPrevSearchLight.BackColor = Color.White;
            picPrevSearchLight.BorderStyle = BorderStyle.FixedSingle;
            picPrevSearchLight.Location = new Point(8, 28);
            picPrevSearchLight.Name = "picPrevSearchLight";
            picPrevSearchLight.Size = new Size(220, 150);
            picPrevSearchLight.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevSearchLight.TabIndex = 1;
            picPrevSearchLight.TabStop = false;
            lblPrevSearchLight.Dock = DockStyle.Top;
            lblPrevSearchLight.Location = new Point(0, 0);
            lblPrevSearchLight.Name = "lblPrevSearchLight";
            lblPrevSearchLight.Size = new Size(236, 24);
            lblPrevSearchLight.TabIndex = 0;
            lblPrevSearchLight.Text = "Поиск - светлая тема";
            lblPrevSearchLight.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevSearchDark.Controls.Add(picPrevSearchDark);
            pnlPrevSearchDark.Controls.Add(lblPrevSearchDark);
            pnlPrevSearchDark.Location = new Point(11, 201);
            pnlPrevSearchDark.Name = "pnlPrevSearchDark";
            pnlPrevSearchDark.Size = new Size(236, 184);
            pnlPrevSearchDark.TabIndex = 3;
            picPrevSearchDark.BackColor = Color.White;
            picPrevSearchDark.BorderStyle = BorderStyle.FixedSingle;
            picPrevSearchDark.Location = new Point(8, 28);
            picPrevSearchDark.Name = "picPrevSearchDark";
            picPrevSearchDark.Size = new Size(220, 150);
            picPrevSearchDark.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevSearchDark.TabIndex = 1;
            picPrevSearchDark.TabStop = false;
            lblPrevSearchDark.Dock = DockStyle.Top;
            lblPrevSearchDark.Location = new Point(0, 0);
            lblPrevSearchDark.Name = "lblPrevSearchDark";
            lblPrevSearchDark.Size = new Size(236, 24);
            lblPrevSearchDark.TabIndex = 0;
            lblPrevSearchDark.Text = "Поиск - тёмная тема";
            lblPrevSearchDark.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevIos.Controls.Add(picPrevIos);
            pnlPrevIos.Controls.Add(lblPrevIos);
            pnlPrevIos.Location = new Point(253, 201);
            pnlPrevIos.Name = "pnlPrevIos";
            pnlPrevIos.Size = new Size(236, 184);
            pnlPrevIos.TabIndex = 4;
            picPrevIos.BackColor = Color.White;
            picPrevIos.BorderStyle = BorderStyle.FixedSingle;
            picPrevIos.Location = new Point(8, 28);
            picPrevIos.Name = "picPrevIos";
            picPrevIos.Size = new Size(220, 150);
            picPrevIos.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevIos.TabIndex = 1;
            picPrevIos.TabStop = false;
            lblPrevIos.Dock = DockStyle.Top;
            lblPrevIos.Location = new Point(0, 0);
            lblPrevIos.Name = "lblPrevIos";
            lblPrevIos.Size = new Size(236, 24);
            lblPrevIos.TabIndex = 0;
            lblPrevIos.Text = "Рабочий стол Apple";
            lblPrevIos.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevAndroid.Controls.Add(picPrevAndroid);
            pnlPrevAndroid.Controls.Add(lblPrevAndroid);
            pnlPrevAndroid.Location = new Point(495, 201);
            pnlPrevAndroid.Name = "pnlPrevAndroid";
            pnlPrevAndroid.Size = new Size(236, 184);
            pnlPrevAndroid.TabIndex = 5;
            picPrevAndroid.BackColor = Color.White;
            picPrevAndroid.BorderStyle = BorderStyle.FixedSingle;
            picPrevAndroid.Location = new Point(8, 28);
            picPrevAndroid.Name = "picPrevAndroid";
            picPrevAndroid.Size = new Size(220, 150);
            picPrevAndroid.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevAndroid.TabIndex = 1;
            picPrevAndroid.TabStop = false;
            lblPrevAndroid.Dock = DockStyle.Top;
            lblPrevAndroid.Location = new Point(0, 0);
            lblPrevAndroid.Name = "lblPrevAndroid";
            lblPrevAndroid.Size = new Size(236, 24);
            lblPrevAndroid.TabIndex = 0;
            lblPrevAndroid.Text = "Рабочий стол Android";
            lblPrevAndroid.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevSplash.Controls.Add(picPrevSplash);
            pnlPrevSplash.Controls.Add(lblPrevSplash);
            pnlPrevSplash.Location = new Point(11, 391);
            pnlPrevSplash.Name = "pnlPrevSplash";
            pnlPrevSplash.Size = new Size(236, 184);
            pnlPrevSplash.TabIndex = 6;
            picPrevSplash.BackColor = Color.White;
            picPrevSplash.BorderStyle = BorderStyle.FixedSingle;
            picPrevSplash.Location = new Point(8, 28);
            picPrevSplash.Name = "picPrevSplash";
            picPrevSplash.Size = new Size(220, 150);
            picPrevSplash.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevSplash.TabIndex = 1;
            picPrevSplash.TabStop = false;
            lblPrevSplash.Dock = DockStyle.Top;
            lblPrevSplash.Location = new Point(0, 0);
            lblPrevSplash.Name = "lblPrevSplash";
            lblPrevSplash.Size = new Size(236, 24);
            lblPrevSplash.TabIndex = 0;
            lblPrevSplash.Text = "Android - Splash";
            lblPrevSplash.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevSwitcher.Controls.Add(picPrevSwitcher);
            pnlPrevSwitcher.Controls.Add(lblPrevSwitcher);
            pnlPrevSwitcher.Location = new Point(253, 391);
            pnlPrevSwitcher.Name = "pnlPrevSwitcher";
            pnlPrevSwitcher.Size = new Size(236, 184);
            pnlPrevSwitcher.TabIndex = 7;
            picPrevSwitcher.BackColor = Color.White;
            picPrevSwitcher.BorderStyle = BorderStyle.FixedSingle;
            picPrevSwitcher.Location = new Point(8, 28);
            picPrevSwitcher.Name = "picPrevSwitcher";
            picPrevSwitcher.Size = new Size(220, 150);
            picPrevSwitcher.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevSwitcher.TabIndex = 1;
            picPrevSwitcher.TabStop = false;
            lblPrevSwitcher.Dock = DockStyle.Top;
            lblPrevSwitcher.Location = new Point(0, 0);
            lblPrevSwitcher.Name = "lblPrevSwitcher";
            lblPrevSwitcher.Size = new Size(236, 24);
            lblPrevSwitcher.TabIndex = 0;
            lblPrevSwitcher.Text = "Android - переключатель";
            lblPrevSwitcher.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevTile.Controls.Add(picPrevTile);
            pnlPrevTile.Controls.Add(lblPrevTile);
            pnlPrevTile.Location = new Point(495, 391);
            pnlPrevTile.Name = "pnlPrevTile";
            pnlPrevTile.Size = new Size(236, 184);
            pnlPrevTile.TabIndex = 8;
            picPrevTile.BackColor = Color.White;
            picPrevTile.BorderStyle = BorderStyle.FixedSingle;
            picPrevTile.Location = new Point(8, 28);
            picPrevTile.Name = "picPrevTile";
            picPrevTile.Size = new Size(220, 150);
            picPrevTile.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevTile.TabIndex = 1;
            picPrevTile.TabStop = false;
            lblPrevTile.Dock = DockStyle.Top;
            lblPrevTile.Location = new Point(0, 0);
            lblPrevTile.Name = "lblPrevTile";
            lblPrevTile.Size = new Size(236, 24);
            lblPrevTile.TabIndex = 0;
            lblPrevTile.Text = "Windows - плитка";
            lblPrevTile.TextAlign = ContentAlignment.MiddleCenter;
            pnlPrevSafari.Controls.Add(picPrevSafari);
            pnlPrevSafari.Controls.Add(lblPrevSafari);
            pnlPrevSafari.Location = new Point(11, 581);
            pnlPrevSafari.Name = "pnlPrevSafari";
            pnlPrevSafari.Size = new Size(236, 184);
            pnlPrevSafari.TabIndex = 9;
            picPrevSafari.BackColor = Color.White;
            picPrevSafari.BorderStyle = BorderStyle.FixedSingle;
            picPrevSafari.Location = new Point(8, 28);
            picPrevSafari.Name = "picPrevSafari";
            picPrevSafari.Size = new Size(220, 150);
            picPrevSafari.SizeMode = PictureBoxSizeMode.Zoom;
            picPrevSafari.TabIndex = 1;
            picPrevSafari.TabStop = false;
            lblPrevSafari.Dock = DockStyle.Top;
            lblPrevSafari.Location = new Point(0, 0);
            lblPrevSafari.Name = "lblPrevSafari";
            lblPrevSafari.Size = new Size(236, 24);
            lblPrevSafari.TabIndex = 0;
            lblPrevSafari.Text = "Safari - Pinned Tab";
            lblPrevSafari.TextAlign = ContentAlignment.MiddleCenter;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1164, 721);
            Controls.Add(flowPreviews);
            Controls.Add(tabsSettings);
            Controls.Add(panelBottom);
            Controls.Add(panelTop);
            MinimumSize = new Size(1000, 640);
            Name = "FaviconForm";
            StartPosition = FormStartPosition.CenterParent;
            Text = "FaviconForge - генератор favicon-пакета";
            panelTop.ResumeLayout(false);
            panelTop.PerformLayout();
            tabsSettings.ResumeLayout(false);
            tabGeneral.ResumeLayout(false);
            tabGeneral.PerformLayout();
            tabFavicon.ResumeLayout(false);
            tabFavicon.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)trkFavRadius).EndInit();
            ((System.ComponentModel.ISupportInitialize)trkFavMargin).EndInit();
            tabIos.ResumeLayout(false);
            tabIos.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)trkIosMargin).EndInit();
            tabAndroid.ResumeLayout(false);
            tabAndroid.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)trkAndroidMargin).EndInit();
            tabWindows.ResumeLayout(false);
            tabWindows.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)trkTileMargin).EndInit();
            tabSafari.ResumeLayout(false);
            tabSafari.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)trkSafariThreshold).EndInit();
            panelBottom.ResumeLayout(false);
            panelBottom.PerformLayout();
            flowPreviews.ResumeLayout(false);
            pnlPrevBrowserLight.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevBrowserLight).EndInit();
            pnlPrevBrowserDark.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevBrowserDark).EndInit();
            pnlPrevSearchLight.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevSearchLight).EndInit();
            pnlPrevSearchDark.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevSearchDark).EndInit();
            pnlPrevIos.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevIos).EndInit();
            pnlPrevAndroid.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevAndroid).EndInit();
            pnlPrevSplash.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevSplash).EndInit();
            pnlPrevSwitcher.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevSwitcher).EndInit();
            pnlPrevTile.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevTile).EndInit();
            pnlPrevSafari.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picPrevSafari).EndInit();
            ResumeLayout(false);
        }

        private System.Windows.Forms.Timer previewTimer;
        private Panel panelTop;
        private Button btnOpenSource;
        private Label lblSourceInfo;
        private TabControl tabsSettings;
        private TabPage tabGeneral;
        private TabPage tabFavicon;
        private TabPage tabIos;
        private TabPage tabAndroid;
        private TabPage tabWindows;
        private TabPage tabSafari;
        private Label lblPathPrefix;
        private TextBox txtPathPrefix;
        private Label lblThemeColorCap;
        private Button btnThemeColor;
        private CheckBox chkPixelArt;
        private CheckBox chkFavBg;
        private Button btnFavColor;
        private Label lblFavMargin;
        private TrackBar trkFavMargin;
        private Label lblFavRadius;
        private TrackBar trkFavRadius;
        private CheckBox chkIosBg;
        private Button btnIosColor;
        private Label lblIosMargin;
        private TrackBar trkIosMargin;
        private Label lblAppleTitleCap;
        private TextBox txtAppleTitle;
        private Label lblAndroidNameCap;
        private TextBox txtAndroidName;
        private Label lblAndroidShortCap;
        private TextBox txtAndroidShort;
        private CheckBox chkAndroidBg;
        private Button btnAndroidColor;
        private Label lblAndroidMargin;
        private TrackBar trkAndroidMargin;
        private CheckBox chkAndroidCircle;
        private Label lblTileColorCap;
        private Button btnTileColor;
        private Label lblTileMargin;
        private TrackBar trkTileMargin;
        private Label lblSafariColorCap;
        private Button btnSafariColor;
        private Label lblSafariThreshold;
        private TrackBar trkSafariThreshold;
        private Panel panelBottom;
        private Button btnGenerateZip;
        private Button btnGenerateFolder;
        private Button btnCopyHtml;
        private Label lblHtml;
        private TextBox txtHtml;
        private FlowLayoutPanel flowPreviews;
        private Panel pnlPrevBrowserLight;
        private Label lblPrevBrowserLight;
        private PictureBox picPrevBrowserLight;
        private Panel pnlPrevBrowserDark;
        private Label lblPrevBrowserDark;
        private PictureBox picPrevBrowserDark;
        private Panel pnlPrevSearchLight;
        private Label lblPrevSearchLight;
        private PictureBox picPrevSearchLight;
        private Panel pnlPrevSearchDark;
        private Label lblPrevSearchDark;
        private PictureBox picPrevSearchDark;
        private Panel pnlPrevIos;
        private Label lblPrevIos;
        private PictureBox picPrevIos;
        private Panel pnlPrevAndroid;
        private Label lblPrevAndroid;
        private PictureBox picPrevAndroid;
        private Panel pnlPrevSplash;
        private Label lblPrevSplash;
        private PictureBox picPrevSplash;
        private Panel pnlPrevSwitcher;
        private Label lblPrevSwitcher;
        private PictureBox picPrevSwitcher;
        private Panel pnlPrevTile;
        private Label lblPrevTile;
        private PictureBox picPrevTile;
        private Panel pnlPrevSafari;
        private Label lblPrevSafari;
        private PictureBox picPrevSafari;
    }
}
